Update README.md
marinac-dev/qdrant pull request #12
Opened 2024-06-12 07:16 UTC by sooonism

- update the version tag to the latest.
- update `search/2` to `search_points/2`.

2024-06-12 11:39 UTC, marinac-dev commented
Hi @sooonism 
Thanks for helping out!
Version change will have to be rejected because it will cause confusion in hex repo. I know I messed up originally, but there is no turning back now - this is my first OS library :")
Other change will be accepted! :)

PS: I have been extremely busy with personal life (the busiest year in my life so far 🥲) but maintaining this library is the very top of my list of priorities

2024-06-12 11:41 UTC, marinac-dev requested changes

2024-06-12 11:41 UTC, marinac-dev commented on README.md
> +    {:qdrant, "~> 0.0.8"}
Please revert this as will cause problems with hex repo

2024-06-13 00:48 UTC, sooonism commented
Hi,
First of all, thanks for creating this git.
I already updated and commited based on your request.
I might occasionally have more pull requests as I foresee I will be heavily using Qdrant.

2024-06-16 22:20 UTC, merged